apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - datasource-configmap.yaml
  - dashboard-provider-configmap.yaml
  - deployment.yaml
  - service.yaml
