{{- if .Values.rbac.create -}}
apiVersion: {{ include "k8s-chaos.rbacApiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-chaos.fullname" . }}-manager-rolebinding
  labels:
    {{- include "k8s-chaos.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-chaos.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-chaos.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}