apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-chaos.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-chaos.labels" . | nindent 4 }}
spec:
  ports:
  {{- if .Values.webhook.enabled }}
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  {{- end }}
  {{- if .Values.metrics.enabled }}
  - name: metrics
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: metrics
  {{- end }}
  selector:
    {{- include "k8s-chaos.selectorLabels" . | nindent 4 }}
