{{- if .Values.webhook.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "k8s-chaos.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "k8s-chaos.labels" . | nindent 4 }}
  {{- if and .Values.webhook.certificate.certManager (not .Values.webhook.certificate.generate) }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "k8s-chaos.fullname" . }}-serving-cert
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "k8s-chaos.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-chaos-gushchin-dev-v1alpha1-chaosexperiment
    {{- if and (not .Values.webhook.certificate.certManager) .Values.webhook.certificate.generate }}
    caBundle: {{ .Files.Get "certs/ca.crt" | b64enc }}
    {{- end }}
  failurePolicy: Fail
  name: vchaosexperiment.kb.io
  rules:
  - apiGroups:
    - chaos.gushchin.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - chaosexperiments
  sideEffects: None
{{- end }}